"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory\
$git_branch\
$git_status
$character
"""
add_newline = false

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = '…/'

[git_branch]
truncation_length = 32
symbol=""
format='[$symbol$branch](bold purple)'

[git_status]
format='$ahead_behind'
